### ISSUE TITLE
Can't compile extension on both Docker and Vagrant

### ISSUE THREAD

**Issue by artzwinger** [concurrent-php/ext-async#109]
Vagrant:

    ubuntu14: relocation
    ubuntu14:  (0x2a) in section `.text'
    ubuntu14: /usr/bin/ld: final link failed: Bad value
    ubuntu14: collect2: error: ld returned 1 exit status
    ubuntu14: make:
    ubuntu14: *** [async.la] Error 1

Docker:

tar: invalid magic
tar: short read

**Comment by martinschroeder** [comment]
This happens if you build the extension on multiple different platforms. It happens when you call `vagrant up` for example. This will create to different virtual machines, the first to start will compile libuv and write `thridparty/lib/libuv.a` and compile just fine. The second machine will detect the file and try to use it, which fails, because the compiled lib is not compatible with the machine.

Vagrant: Start machines using `vagrant up ubuntu14` or `vagrant up ubuntu18`, never start both of them. If you need to switch machines make sure to delete `thrirdparty/lib/libuv.a` before launching the new machine.

I have to look into the docker image sometime later... i dont know if (and how) it works.

**Comment by martinschroeder** [comment]
Update: I have changed the vagrant config file to autostart `ubuntu18` only, you can call `vagrant up` just fine now. The part about deleting `thirdparty/lib/libuv.a` is still needed when switching machines.

**Comment by artzwinger** [comment]
Hi Martin, thank you for fixing Vagrantfile. I have created PR for Dockerfile.

**Comment by martinschroeder** [comment]
Thanks for PR #110, i have merged it right away. I am closing this issue as it has been solved (i will update the install section in the readme file with a warning about compiling the extension on multiple different platforms from the same source directory soon).
