### ISSUE TITLE
Integrate µWebSockets (C++ lib HTTP/WebSocket)

### ISSUE THREAD

**Issue by uasan** [concurrent-php/ext-async#114]
Hello.
I know that your library is low-level API.

But it would be very useful in her to have a built-in productive implementation of `HTTP` and `WebSocket` protocols.

There is an excellent library `µWebSockets`: https://github.com/uNetworking/uWebSockets

There is not enough native extension for PHP.
Thanks.

**Comment by azjezz** [comment]
i don't think this should be part of `ext-async`, since it can be implemented in user-land, and has been already implemented : https://github.com/concurrent-php/http and https://github.com/concurrent-php/websockets

if you are looking for a networking API, you should probably take a look at https://github.com/swoole/swoole-src instead.

**Comment by uasan** [comment]
I am looking for a light and very fast lib HTTP/WebSocket, in the world of Node.js, this is µWebSockets.

>  https://github.com/concurrent-php/http and https://github.com/concurrent-php/websockets

This is a high-level IPA, obviously it is not so fast, we also have such )

> https://github.com/swoole/swoole-src

Yes i know, but he pulls the whole framework swoole

**Comment by martinschroeder** [comment]
I will not provide more advanced protocols (like HTTP) as part of this extension. The basic idea is to expose everything that libuv has to offer in an easy to use way with a clean and simple API. I do not want to go the `swoole` way and provide support for everything because it will be way too hard to maintain and keep up with all the dependencies.
