### ISSUE TITLE
Nested scheduler runs

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#26]
Sometimes the scheduler runs nested (verified via stack traces in `Task::runLoop`). If it returns, it fails all current `await`s that are not done, yet. This behavior is wrong, because the outer run might resolve the `Deferred` that's awaited. I think the actual solution here is to fix the nested runs, which shouldn't happen.

See [here](https://github.com/amphp/process/commit/991ee9079b25f46c9a315286724660f2545a93b6) for a test case.

**Comment by martinschroeder** [comment]
This should be fixed by now. I have added scheduler state checking in all places. I am assuming that you are calling `await()` from an invalid context somewhere (like a watcher registered with the event loop). I added checks to verify that await is supported by the calling context. This could help with finding out where the nested call is happening.

**Comment by kelunik** [comment]
Does `Task::await()` throw an exception if it's not allowed in the current context?

**Comment by martinschroeder** [comment]
Yes, i added that today and also made sure that you cannot `await()` in a callback being used to `combine()` or `transform()`. I added a test case using a simplified event loop and it throws when i try to await in a timer watcher.

**Comment by kelunik** [comment]
@martinschroeder Thanks! I guess we can close this issue then.

`amphp/amp@ext-async` is pretty small now, maybe we could `require-dev` it for test cases?
