### ISSUE TITLE
Killing pending tasks

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#33]
For tests there should be some way to kill pending tasks. Some details have already been discussed in #31. An example of a pending task that should be killed instead of awaited can be found [here](https://github.com/amphp/amp/blob/b037868a98b99f2fed1d36edc871f849ca08b4cb/test/TimeoutTest.php#L68-L70).

I think for a start it would be good to have `Task::kill(Task)` or maybe even `$task->kill()`. I'm not sure whether there will be any need for killing tasks that the test doesn't have access to.

**Comment by martinschroeder** [comment]
I do not like the kill-based approach because it allows one to kill any task that you have access to. Since tasks are awaitables and can be passed around in an application i think this is a very risky thing to add.

I think it would be better to extend the scheduler with a way to dispose of all unfinished tasks. This way only code that has access to the scheduler can kill tasks and the scheduler will not be passed around. A test listener could have access to the default scheduler and call that method (maybe named `shutdown()` or something like that).

**Comment by kelunik** [comment]
> I do not like the kill-based approach because it allows one to kill any task that you have access to. 

What's so bad about that? Sure, with great power comes great responsibility, but I think protecting the user from himself is a minor concern for now. It's more important to have something working IMO. Once we played around with it, we'll have a better opinion what we actually need.

I'd probably add `Task::dispose()` which causes any pending and future await to throw an exception, maybe allow a custom exception to be passed to `Task::dispose()`.

**Comment by martinschroeder** [comment]
I addressed the disposal of running tasks in the above PR. You have to replace `TaskScheduler::setDefaultScheduler()` with `TaskScheduler::push()` in your autoload file. You can also refactor the `LoopReset` listener like this:
```php
public function startTest(Test $test) {
```

**Comment by kelunik** [comment]
The `TaskScheduler::unregister()` runs the pending tasks to completion as far as I understand? Not sure whether that's always desired, but it's probably fine.

**Comment by martinschroeder** [comment]
Yes, unregister() does run all tasks to completion. I did not want to implement the scheduler switching in two methods, i would have preferred a single method that takes a scheduler and a callback. The split into two methods is a concession to your test listener...
