### ISSUE TITLE
Deferred::combine seems to be broken

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#43]
[I used `Task::await(all($awaitables));`](https://github.com/amphp/sync/blob/f2b2968735716a6b6ec9b849536c90b09fd9ee5c/test/SynchronizedTest.php#L34-L35), but that failed with an awaitable not resolved error. It works if I await the awaitables sequentially, so there must be something wrong with `Deferred::combine`. I guess it doesn't work correctly if not all awaitables are resolved, yet.

**Comment by martinschroeder** [comment]
Are you sure this is caused by `Deferred::combine()`. I create a new test case https://github.com/concurrent-php/ext-async/blob/master/tests/309-deferred-combine-tasks.phpt that used both pending and finished tasks that finish after a delay. The test works just fine. Could the error be related to some kind of race condition instead?

You could try using the `all()` combinator i provided in https://github.com/concurrent-php/ext-async/issues/14 instead, it does not use `Deferred::combine()`, if it works i really have to do some debugging using your example test case...

**Comment by martinschroeder** [comment]
@kelunik I checked out you project and changed it back to use `all()` like this:
```php
$awaitables = [];
foreach (\range(0, 2) as $value) {
    $awaitables[] = Task::async(function () use ($mutex, $callback, $value) {
        return synchronized($mutex, $callback, $value);
    });
}

$this->assertSame(\range(0, 2), Task::await(all($awaitables)));
```
It works just fine now and i do not get any errors...
