### ISSUE TITLE
Symfony or similar full stack framework integration

### ISSUE THREAD

**Issue by hariszukanovic** [concurrent-php/ext-async#47]
Do you see ext-async to be usable (to give a performance boost) integrated into Symfony or similar framework?
Are there any plans of such integration?

**Comment by martinschroeder** [comment]
The async extension allows one to use async APIs as if they were synchronous. It is possible to use an async HTTP server (amphp or reactphp) to power a standard PHP framework or application. The advantage of this approach is that there is no re-loading of code in between multiple HTTP requests providing a significant boost to performance (see [PPM](https://github.com/php-pm/php-pm) for a somewhat related example). If you replace blocking operations (network, filesystem, DB access, ...) in frameworks like Symfony with async counterparts it allows you to go even faster due to reduced idle times of processes / threads.

There a no plans for integration with an existing framework yet, i am still in the process of creating a solid foundation for async IO support (needs a builtin event-loop). I am sure that it will be quite easy to provide some basic integration once the `async` extension has matured a little more.

**Comment by kelunik** [comment]
I think it's not worth working on that until the extension is pretty stable. I vote to close this issue for now with the `revisit` label.

**Comment by martinschroeder** [comment]
I implemented and [HTTP client and server](https://github.com/concurrent-php/http) using PSR-7 / PSR-18 that you can use to benefit from `ext-async` in an existing application. You still need to write some glue code to map PSR request / response to Symfony request / response but it should work out just fine. I recommend to add `async.dns=1` and `async.filesystem=1` to `php.ini` in order to benefit from non-blocking DNS lookups and filesystem IO.
