### ISSUE TITLE
Libaco

### ISSUE THREAD

**Issue by joelwurtz** [concurrent-php/ext-async#51]
Not sure if you see this, but may be interesting to use this lib : https://github.com/hnes/libaco

**Comment by martinschroeder** [comment]
I have not seen this library yet. The thing that is very interesting about libaco is the shared stack feature. As far as assembler context switching is converned it seems to be pretty much the same as boost.context without support for any ABI besides x86 and x64.

I will have a deeper look into the stack sharing some time in the future because it might be interesting to have that feature in the extension. It might also be possible to implement an additional fiber backend based on libaco since backends are abstracted behind a simple API.

**Comment by martinschroeder** [comment]
I am marking this issue as `revisit topic` and will close it for now. It might be interesting for a future version, but at this time i think the implemented backends are sufficient and i want to spend my time working some more on the proposed features and APIs.

**Comment by martinschroeder** [comment]
I am removing the `revisit` label because the development of `libaco` seems to have stalled and platform support is far behind what `boost.context` offers. While the idea of a shared stack is nice it is also very dangerous because PHP / Zend engine at times passes pointers to stack allocated variables around that would lead to bugs or segfaults when stack contents are copied and overwritten.
