### ISSUE TITLE
Closing readable streams

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#67]
> The optional error argument of close() allows to pass in an error that will be set as previous error when failing a read operation.

What's the actual exception being thrown? What's the behavior of `read()` operations if a stream is `close()`'d after the stream is already at EOF? Does it throw the exception or does it return `null`?

**Comment by martinschroeder** [comment]
The actual exception being thrown is `StreamClosedException`. The exception will be thrown if you read from a stream that has been closed by calling `close()`. This also happens when the stream has reached EOF before being closed. I want to keep it consistent: every call to `read()` after `close()` has been called must throw a `StreamClosedException`. I will update the readme file to include this.
