### ISSUE TITLE
Concurrent stream reads

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#68]
I think concurrent stream reads should result in an exception. Two concurrent readers will generally result in unexpected behavior, thus it's better to forbid it entirely.

**Comment by martinschroeder** [comment]
Concurrent reads are supported for the time being because it came for free with the way i implemented streams. I do however agree that this is not an ideal situation and it can be changed. I could add a `PendingReadException` and update the docs to state that this exception must be thrown if `read()` is called before any previous call to `read()` has completed.

**Comment by martinschroeder** [comment]
I added the `PendingReadException` and updatet the readme file and the readable pipe implementation. Concurrent reads are not supported anymore.
