### ISSUE TITLE
Remove StreamWatcher

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#69]
I don't see any reason for `StreamWatcher` to exist if we have streams implemented in code as an abstraction.

**Comment by martinschroeder** [comment]
Many use cases for `StreamWatcher` can be covered by streams, an exception are socket servers that need to wait for a server socket to become readable before accepting a new client connection. That being said it will take some time to implement everything as a stream and the `StreamWatcher` can be used to implement streams in userland until i manage to do it in C.

I will look into libuv's support for TCP streams in the future and will attempt to create stream implementations for that. I also need to look into TLS support because it will be required and i am not sure if i can reuse PHP streams for that...

**Comment by martinschroeder** [comment]
TCP sockets and (child) process pipes have been implemented in C code, no need for `StreamWatcher` in these cases anymore. Support for (current process) `STDIN`, `STDOUT` and `STDERR` as streams is missing, this is the remaining use case for the stream watcher...

**Comment by martinschroeder** [comment]
PR #104 introduced support for non-blocking `STDIN`, `STDOUT` and `STDERR`. This should further reduce the number of cases where having the stream watcher is useful. I also provide async versions of PHP socket streams (`async-tcp`, ...) that can be used in places where a PHP stream is required. Support for UNIX domain sockets (and maybe named pipes on Windows?) is still missing but i will add that soon

**Comment by martinschroeder** [comment]
I decided to keep `Poll` (formerly known as `StreamWatcher`) to be used in edge cases where you have to observe a provided fd (this should never happen for most users). I added a section to the readme file that clearly states that `Poll` should not be used most of the time and can crash the PHP process if more than a single poll is created for the same resource.
