### ISSUE TITLE
Task local sockets

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#91]
@martinschroeder Can streams be shared and work with multiple schedulers? Or how do I share one default DNS resolver per task scheduler? With Amp we had https://github.com/amphp/dns/blob/836b0896b0105298373669754ece8ad8577c0854/lib/functions.php#L10-L31, but the current context doesn't allow for that, as that's immutable. 

Do you have any advice?

**Comment by martinschroeder** [comment]
Streams cannot be shared across schedulers because each scheduler has a dedicated uv event loop that does not allow for sharing resources. This basically means that a single component (like a DNS resolver) cannot cover more than a single scheduler. Using `Context` does not seem to be appropriate here and the context can be shared across schedulers while DNS resolver internals cannot be shared.

There needs to be a mechanism that allows for scoping instances to a scheduler's lifetime in order to achieve your goal. A possible solution could be to add a (static) registry to the task scheduler. This would allow us to register a factory function under a registry key (key is a fully qualified class name). The scheduler calls the factory function upon first access and reuses the created object instances afterwards. Something like this:
```php
final class TaskScheduler {
    public static function get(string $key): object { }
    public static function register(string $key, callable $factory): ?callable { }
}

TaskScheduler::register(Resolver::class, function () {
    return new DefaultResolver();
});

$resolver = TaskScheduler::get(Resolver::class);
```
The scheduler would enforce the factory callback to return an object that is an instance of the `$key` type (which makes it kind of type-safe to use). The `register()` method would return the previous factory callback (or NULL if none is registered), to allow switching the factory out and reverting to the previous one in a `try` / `finally` block.

**Comment by martinschroeder** [comment]
I implemented support for scheduler-managed components (as outlined in my previous comment) in #116. It also provides a new contract for userland DNS resolvers, that is deeply integrated with all DNS calls within the extension.
