### ISSUE TITLE
Add ReadableStream::isEof

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#92]
It'd be useful to check if a stream is at `EOF` without actually reading from it. One such use case would be checking if a socket is still alive in the socket pool for Artax, out HTTP client.

**Comment by martinschroeder** [comment]
AFAIK the only way to reliably know if a socket is at EOF is to try a send or recv and check the returned error code. I do get your point about doing this kind of thing in a connection pool. It might be possible to add `isReadable()` / `isWritable()` to `SocketStream` to allow for such a check (there are function provided by `libuv` to do this). However this check is not reliable as the socket might crash between the check and using it afterwards so you need to be prepared to recover from errors by checking out a new socket from the pool anyways...

**Comment by martinschroeder** [comment]
I enhanced the `SocketStream` API with a new method `isAlive()` in PR #111. If it returns `false` you know that the stream has been closed (local or remote). An attempt to perform IO after `isAlive()` returned `true` might still fail due to a race condition (socket closed after `isAlive()` has been called). Also note that `isAlive()` will immediately return `true` if there is readable data buffered by the socket stream.
