### ISSUE TITLE
SocketStream::writeAsync

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#94]
Why does `SocketStream::writeAsync()` exist over just `WritableStream::write()`? When would I use that?

**Comment by martinschroeder** [comment]
Using `write` will block (async blocking, not actually blocking the program / thread) the current task until the write operation has eighter completed or failed. If you use `writeAsync()` instead it will never (async) block, it will try to write data to the underlying (socket) resource. If not all data can be written (flushed to network buffer) immediately it will be queued up for send. The call to `writeAsync()` returns the number of bytes that have been queued for send. Order of transmission is preserved and messages are not interleaved (this is guranteed by `libuv` that provides the actual send queue).

You can use `writeAsync` whenever you want to send data without actually waiting for an ACK. One good use case for this is sending messages (especially broadcast) in a WebSocket server. You don't want the sending task to do (async) blocking calls to `write()` in a loop. You also want to avoid the sender to be blocked in case the receivers network buffer is full or the remote peer is slow for some reason. In such cases it is better to just write data without blocking and check the number of queued bytes (as returned by `writeAsync()`). If the queue gets too large mark the socket as "slow" and have some kind of a GC timer job that can kick the client if it does not catch up. That job can use `SocketStream::getWriteQueueSize()` to check if the client has consumed enough data.

Another interesting use case is a logger that transmits data over a network connection. You do not want to spend time waiting for the logger in your app to avoid a performance penalty.

You can usually come up with another solution to these problems at the cost of spawning additional tasks and using some kind of channel to communicate but this increases the number of tasks and memory usage.

**Comment by kelunik** [comment]
That's exactly the way I would have done it, using additional tasks. Maybe we can have an additional construct that avoids creating tasks, so we don't need to duplicate as many methods?

**Comment by martinschroeder** [comment]
I implemented function interceptors (in C code) that allow for async writes without additional tasks and without async-suffix methods. Interceptors have been added for `TcpSocket::write()`, `Pipe::write()` and `UdpSocket::send()` as these should be the most common use cases. This requires some code changes:
```php
$socket->writeAsync('some data');

// Must be changed to:
Task::async([$socket, 'write'], 'some data');

// Which could (maybe someday) be streamlined using keywords:
async $socket->write('some data');
```
The return type of `Task::async()` has been generalized from `Task` to `Awaitable` to allow for specialized implementations instead of a general purpose task. The returned awaitable can be used to react to failed async opertaions. Not assigning the return value (as in the above example) will not even create an awaitable at all and is basically exactly what `writeAsync()` did.
